/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/trip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Demo Trip */
        get: operations["get_demo_trip_api_v1_demo_trip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Trip Candidate */
        post: operations["parse_trip_candidate_api_v1_trips_candidates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/candidates/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Trip Image */
        post: operations["parse_trip_image_api_v1_trips_candidates_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Decision */
        post: operations["preview_decision_api_v1_decisions_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Question */
        post: operations["answer_question_api_v1_assistant_questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Reminder */
        post: operations["preview_reminder_api_v1_reminders_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/action-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose Action */
        post: operations["propose_action_api_v1_action_proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/privacy/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Privacy Export */
        get: operations["privacy_export_api_v1_privacy_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/privacy/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_v1_privacy_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionProposal */
        ActionProposal: {
            /** Proposal Id */
            proposal_id: string;
            /**
             * Action Type
             * @enum {string}
             */
            action_type: "open_map" | "open_ride_hailing";
            /**
             * Status
             * @constant
             */
            status: "awaiting_user_confirmation";
            /** Label */
            label: string;
            /** Parameters Preview */
            parameters_preview: {
                [key: string]: string;
            };
            /** Deep Link */
            deep_link: string;
            /** Fallback Url */
            fallback_url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Requires Payment
             * @default false
             * @constant
             */
            requires_payment: false;
            /**
             * Automatic Booking
             * @default false
             * @constant
             */
            automatic_booking: false;
        };
        /** ActionProposalRequest */
        ActionProposalRequest: {
            trip: components["schemas"]["TripInput"];
            decision: components["schemas"]["DepartureDecision"];
            /**
             * Action Type
             * @enum {string}
             */
            action_type: "open_map" | "open_ride_hailing";
        };
        /** AirportProcessSnapshot */
        AirportProcessSnapshot: {
            /** Airport */
            airport: string;
            /** Terminal */
            terminal: string;
            /** Checkin Minutes */
            checkin_minutes: number;
            /** Security Minutes */
            security_minutes: number;
            /** Walking Minutes */
            walking_minutes: number;
            /** Gate Distance Meters */
            gate_distance_meters?: number | null;
            /**
             * Accessibility Extra Minutes
             * @default 0
             */
            accessibility_extra_minutes: number;
            metadata: components["schemas"]["SourceMetadata"];
        };
        /** AssistantAnswer */
        AssistantAnswer: {
            /** Answer */
            answer: string;
            /** Cited Evidence Ids */
            cited_evidence_ids: string[];
            /** Provider */
            provider: string;
            /**
             * Evidence Only
             * @default true
             * @constant
             */
            evidence_only: true;
        };
        /** AssistantQuestionRequest */
        AssistantQuestionRequest: {
            /** Question */
            question: string;
            decision: components["schemas"]["DecisionResponse"];
        };
        /** AviationWeatherSnapshot */
        AviationWeatherSnapshot: {
            /** Station Icao */
            station_icao: string;
            /** Raw Metar */
            raw_metar: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Flight Category
             * @enum {string}
             */
            flight_category: "VFR" | "MVFR" | "IFR" | "LIFR" | "UNKNOWN";
            /** Visibility Km */
            visibility_km?: number | null;
            /** Wind Speed Kph */
            wind_speed_kph?: number | null;
            /** Temperature C */
            temperature_c?: number | null;
            metadata: components["schemas"]["SourceMetadata"];
        };
        /** Body_parse_trip_image_api_v1_trips_candidates_image_post */
        Body_parse_trip_image_api_v1_trips_candidates_image_post: {
            /** Image */
            image: string;
            /**
             * Departure Place
             * @default 待确认出发地
             */
            departure_place: string;
            /**
             * Checked Baggage
             * @default false
             */
            checked_baggage: boolean;
            /** @default cautious */
            risk_profile: components["schemas"]["RiskProfile"];
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /** Service */
            service: string;
            /** Version */
            version: string;
            /**
             * Data Scope
             * @enum {string}
             */
            data_scope: "synthetic" | "mixed" | "live";
            /** Provider */
            provider: string;
            /** Planned Model */
            planned_model: string;
            /** Features */
            features: string[];
            /** Guarded Features */
            guarded_features: string[];
            /** Blocked Actions */
            blocked_actions: string[];
            /** Sources */
            sources: components["schemas"]["SourceStatus"][];
        };
        /** Coordinates */
        Coordinates: {
            /** Longitude */
            longitude: number;
            /** Latitude */
            latitude: number;
        };
        /** DecisionComponent */
        DecisionComponent: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Minutes */
            minutes: number;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** DecisionResponse */
        DecisionResponse: {
            trip: components["schemas"]["TripInput"];
            context: components["schemas"]["JourneyContext"];
            decision: components["schemas"]["DepartureDecision"];
            /** Evidence */
            evidence: components["schemas"]["EvidenceItem"][];
            /** Assistant Summary */
            assistant_summary: string;
            /** Verified */
            verified: boolean;
            runtime: components["schemas"]["RuntimeBoundary"];
        };
        /** DeleteResponse */
        DeleteResponse: {
            /**
             * Deleted
             * @constant
             */
            deleted: true;
            /** Scope */
            scope: string;
            /** Note */
            note: string;
        };
        /** DepartureDecision */
        DepartureDecision: {
            /**
             * Recommended Leave At
             * Format: date-time
             */
            recommended_leave_at: string;
            /**
             * Latest Reasonable Leave At
             * Format: date-time
             */
            latest_reasonable_leave_at: string;
            /**
             * Target Terminal Arrival
             * Format: date-time
             */
            target_terminal_arrival: string;
            /**
             * Boarding Start At
             * Format: date-time
             */
            boarding_start_at: string;
            /**
             * Checkin Close At
             * Format: date-time
             */
            checkin_close_at: string;
            /**
             * Scheduled Departure
             * Format: date-time
             */
            scheduled_departure: string;
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "low" | "medium" | "high";
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /** Confidence Window Minutes */
            confidence_window_minutes: number;
            /** Components */
            components: components["schemas"]["DecisionComponent"][];
            /** Binding Constraints */
            binding_constraints: string[];
            /** Assumptions */
            assumptions: string[];
            /** Missing Evidence */
            missing_evidence: string[];
            /**
             * Policy Version
             * @default decision-policy-0.4.0
             */
            policy_version: string;
        };
        /** DisruptionSignal */
        DisruptionSignal: {
            /** Signal Id */
            signal_id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "event" | "construction" | "closure" | "accident" | "social_signal";
            /** Label */
            label: string;
            /**
             * Impact Start
             * Format: date-time
             */
            impact_start: string;
            /**
             * Impact End
             * Format: date-time
             */
            impact_end: string;
            /** Impact Minutes */
            impact_minutes: number;
            /**
             * Route Intersection
             * @enum {string}
             */
            route_intersection: "confirmed" | "possible" | "unknown";
            metadata: components["schemas"]["SourceMetadata"];
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Evidence Id */
            evidence_id: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Source */
            source: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "user_confirmed" | "official_api" | "official_public" | "public_feed" | "configured_rule" | "synthetic_rule" | "derived";
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Fresh Until */
            fresh_until?: string | null;
            /** Confidence */
            confidence: number;
            /**
             * Status
             * @enum {string}
             */
            status: "confirmed" | "live" | "configured" | "synthetic" | "derived" | "stale";
            /**
             * Scope
             * @default
             */
            scope: string;
            /**
             * Completeness
             * @default complete
             * @enum {string}
             */
            completeness: "complete" | "partial" | "unavailable";
            /** Source Url */
            source_url?: string | null;
        };
        /** FlightSnapshot */
        FlightSnapshot: {
            /** Flight Number */
            flight_number: string;
            /**
             * Status
             * @enum {string}
             */
            status: "scheduled" | "delayed" | "cancelled" | "unknown";
            /**
             * Scheduled Departure
             * Format: date-time
             */
            scheduled_departure: string;
            /** Estimated Departure */
            estimated_departure?: string | null;
            /** Terminal */
            terminal: string;
            /** Gate */
            gate?: string | null;
            /**
             * Checkin Open At
             * Format: date-time
             */
            checkin_open_at: string;
            /**
             * Checkin Close At
             * Format: date-time
             */
            checkin_close_at: string;
            /**
             * Boarding Start At
             * Format: date-time
             */
            boarding_start_at: string;
            /**
             * Boarding Close At
             * Format: date-time
             */
            boarding_close_at: string;
            /** Delay Probability */
            delay_probability: number;
            metadata: components["schemas"]["SourceMetadata"];
        };
        /** FlightTelemetrySnapshot */
        FlightTelemetrySnapshot: {
            /** Callsign */
            callsign: string;
            /** Icao24 */
            icao24: string;
            /**
             * State
             * @enum {string}
             */
            state: "airborne" | "ground" | "unknown";
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Altitude Meters */
            altitude_meters?: number | null;
            /** Groundspeed Kph */
            groundspeed_kph?: number | null;
            /** Track Degrees */
            track_degrees?: number | null;
            /**
             * Last Contact At
             * Format: date-time
             */
            last_contact_at: string;
            metadata: components["schemas"]["SourceMetadata"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /**
             * Data Scope
             * @enum {string}
             */
            data_scope: "synthetic" | "mixed" | "live";
        };
        /** JourneyContext */
        JourneyContext: {
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Data Scope
             * @enum {string}
             */
            data_scope: "synthetic" | "mixed" | "live";
            flight: components["schemas"]["FlightSnapshot"];
            airport: components["schemas"]["AirportProcessSnapshot"];
            route: components["schemas"]["RouteSnapshot"];
            weather: components["schemas"]["WeatherSnapshot"];
            flight_telemetry?: components["schemas"]["FlightTelemetrySnapshot"] | null;
            aviation_weather?: components["schemas"]["AviationWeatherSnapshot"] | null;
            /** Disruptions */
            disruptions: components["schemas"]["DisruptionSignal"][];
            /** Missing Sources */
            missing_sources: string[];
            /** Warnings */
            warnings: string[];
        };
        /** PrivacyExport */
        PrivacyExport: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Persistence
             * @enum {string}
             */
            persistence: "none" | "ephemeral";
            /** Stored Personal Data */
            stored_personal_data: unknown[];
            /** Note */
            note: string;
        };
        /** ReminderPreview */
        ReminderPreview: {
            /** Reminder Id */
            reminder_id: string;
            /**
             * Remind At
             * Format: date-time
             */
            remind_at: string;
            /** Title */
            title: string;
            /** Message */
            message: string;
            /**
             * Status
             * @constant
             */
            status: "preview";
            /** Channel Options */
            channel_options: ("calendar" | "web_notification" | "wechat_subscription")[];
            /**
             * Requires User Consent
             * @default true
             * @constant
             */
            requires_user_consent: true;
            /** Idempotency Key */
            idempotency_key: string;
            /** Calendar Ics */
            calendar_ics: string;
        };
        /** ReminderPreviewRequest */
        ReminderPreviewRequest: {
            trip: components["schemas"]["TripInput"];
            decision: components["schemas"]["DepartureDecision"];
            /**
             * Lead Hours
             * @default 24
             */
            lead_hours: number;
        };
        /**
         * RiskProfile
         * @enum {string}
         */
        RiskProfile: "standard" | "cautious" | "very_cautious";
        /** RouteSnapshot */
        RouteSnapshot: {
            /** Origin Label */
            origin_label: string;
            /** Destination Label */
            destination_label: string;
            /** Distance Km */
            distance_km?: number | null;
            /** P50 Minutes */
            p50_minutes: number;
            /** P90 Minutes */
            p90_minutes: number;
            /** Pickup Minutes */
            pickup_minutes: number;
            /**
             * Congestion Level
             * @enum {string}
             */
            congestion_level: "low" | "medium" | "high" | "unknown";
            /**
             * Incident Delay Minutes
             * @default 0
             */
            incident_delay_minutes: number;
            metadata: components["schemas"]["SourceMetadata"];
        };
        /** RuntimeBoundary */
        RuntimeBoundary: {
            /**
             * Data Scope
             * @enum {string}
             */
            data_scope: "synthetic" | "mixed" | "live";
            /** Provider */
            provider: string;
            /** Model */
            model?: string | null;
            /**
             * Persistence
             * @enum {string}
             */
            persistence: "none" | "ephemeral";
            /**
             * Automatic Booking
             * @constant
             */
            automatic_booking: false;
            /**
             * Reminder Delivery
             * @enum {string}
             */
            reminder_delivery: "preview_only" | "configured";
        };
        /** SourceMetadata */
        SourceMetadata: {
            /** Source Id */
            source_id: string;
            /** Source Name */
            source_name: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "user_confirmed" | "official_api" | "official_public" | "public_feed" | "configured_rule" | "synthetic_rule" | "derived";
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Fresh Until */
            fresh_until?: string | null;
            /** Scope */
            scope: string;
            /**
             * Completeness
             * @enum {string}
             */
            completeness: "complete" | "partial" | "unavailable";
            /**
             * Freshness
             * @enum {string}
             */
            freshness: "fresh" | "stale" | "not_applicable";
            /** Confidence */
            confidence: number;
            /** Source Url */
            source_url?: string | null;
            /** License Note */
            license_note?: string | null;
            /** Warnings */
            warnings?: string[];
        };
        /** SourceStatus */
        SourceStatus: {
            /** Source Id */
            source_id: string;
            /** Label */
            label: string;
            /**
             * Category
             * @enum {string}
             */
            category: "flight" | "airport" | "route" | "weather" | "events" | "model" | "ocr";
            /**
             * Mode
             * @enum {string}
             */
            mode: "synthetic" | "configured" | "available" | "blocked" | "unavailable";
            /** Freshness Minutes */
            freshness_minutes?: number | null;
            /** Requires Secret */
            requires_secret: boolean;
            /** Enabled */
            enabled: boolean;
            /** Detail */
            detail: string;
        };
        /** TripCandidate */
        TripCandidate: {
            /** Candidate Id */
            candidate_id: string;
            source_type: components["schemas"]["TripSourceType"];
            /** Source Summary */
            source_summary: string;
            /**
             * Itinerary Source
             * @enum {string}
             */
            itinerary_source: "manual" | "ctrip" | "umetrip" | "airline" | "calendar" | "other";
            /** Flight Number */
            flight_number?: string | null;
            /** Departure Airport */
            departure_airport?: string | null;
            /** Destination Airport */
            destination_airport?: string | null;
            /** Terminal */
            terminal?: string | null;
            /** Scheduled Departure */
            scheduled_departure?: string | null;
            /** Departure Place */
            departure_place: string;
            /** Checked Baggage */
            checked_baggage: boolean;
            risk_profile: components["schemas"]["RiskProfile"];
            /** Field Confidence */
            field_confidence: {
                [key: string]: number;
            };
            /** Missing Fields */
            missing_fields: string[];
            /** Warnings */
            warnings: string[];
            /** Redactions Applied */
            redactions_applied: string[];
            /**
             * Needs User Confirmation
             * @default true
             * @constant
             */
            needs_user_confirmation: true;
        };
        /** TripInput */
        TripInput: {
            /** Flight Number */
            flight_number: string;
            /** Departure Airport */
            departure_airport: string;
            /** Destination Airport */
            destination_airport?: string | null;
            /**
             * Terminal
             * @default 待确认
             */
            terminal: string;
            /**
             * Scheduled Departure
             * Format: date-time
             */
            scheduled_departure: string;
            /** Departure Place */
            departure_place: string;
            departure_coordinates?: components["schemas"]["Coordinates"] | null;
            /**
             * Checked Baggage
             * @default false
             */
            checked_baggage: boolean;
            /**
             * Accessibility Assistance
             * @default false
             */
            accessibility_assistance: boolean;
            /** @default cautious */
            risk_profile: components["schemas"]["RiskProfile"];
            /**
             * Live Data Consent
             * @default false
             */
            live_data_consent: boolean;
            /**
             * Model Egress Consent
             * @default false
             */
            model_egress_consent: boolean;
            /**
             * Itinerary Source
             * @default manual
             * @enum {string}
             */
            itinerary_source: "manual" | "ctrip" | "umetrip" | "airline" | "calendar" | "other";
            /** User Disruption Notes */
            user_disruption_notes?: string[];
        };
        /** TripParseRequest */
        TripParseRequest: {
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "text" | "ics";
            /** Content */
            content: string;
            /**
             * Departure Place
             * @default 待确认出发地
             */
            departure_place: string;
            /**
             * Checked Baggage
             * @default false
             */
            checked_baggage: boolean;
            /** @default cautious */
            risk_profile: components["schemas"]["RiskProfile"];
        };
        /**
         * TripSourceType
         * @enum {string}
         */
        TripSourceType: "manual" | "text" | "ics" | "image";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeatherSnapshot */
        WeatherSnapshot: {
            /** Summary */
            summary: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "none" | "minor" | "moderate" | "severe" | "unknown";
            /** Precipitation Probability */
            precipitation_probability?: number | null;
            /** Wind Speed Kph */
            wind_speed_kph?: number | null;
            /** Buffer Minutes */
            buffer_minutes: number;
            metadata: components["schemas"]["SourceMetadata"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatus"][];
                };
            };
        };
    };
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    get_demo_trip_api_v1_demo_trip_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripInput"];
                };
            };
        };
    };
    parse_trip_candidate_api_v1_trips_candidates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_trip_image_api_v1_trips_candidates_image_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_trip_image_api_v1_trips_candidates_image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_decision_api_v1_decisions_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_question_api_v1_assistant_questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantAnswer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_reminder_api_v1_reminders_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_action_api_v1_action_proposals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionProposalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionProposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    privacy_export_api_v1_privacy_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivacyExport"];
                };
            };
        };
    };
    delete_session_api_v1_privacy_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
        };
    };
}
