/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/trip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Demo Trip */
        get: operations["get_demo_trip_api_v1_demo_trip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Decision */
        post: operations["preview_decision_api_v1_decisions_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /** Service */
            service: string;
            /** Version */
            version: string;
            /**
             * Data Scope
             * @constant
             */
            data_scope: "synthetic";
            /**
             * Provider
             * @constant
             */
            provider: "fake";
            /**
             * Planned Model
             * @constant
             */
            planned_model: "gpt-5.6-sol";
            /** Features */
            features: string[];
            /** Blocked Actions */
            blocked_actions: string[];
        };
        /** DecisionComponent */
        DecisionComponent: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Minutes */
            minutes: number;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** DecisionResponse */
        DecisionResponse: {
            trip: components["schemas"]["TripInput"];
            decision: components["schemas"]["DepartureDecision"];
            /** Evidence */
            evidence: components["schemas"]["EvidenceItem"][];
            /** Assistant Summary */
            assistant_summary: string;
            /** Verified */
            verified: boolean;
            runtime: components["schemas"]["RuntimeBoundary"];
        };
        /** DepartureDecision */
        DepartureDecision: {
            /**
             * Recommended Leave At
             * Format: date-time
             */
            recommended_leave_at: string;
            /**
             * Latest Reasonable Leave At
             * Format: date-time
             */
            latest_reasonable_leave_at: string;
            /**
             * Target Terminal Arrival
             * Format: date-time
             */
            target_terminal_arrival: string;
            /**
             * Scheduled Departure
             * Format: date-time
             */
            scheduled_departure: string;
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "low" | "medium" | "high";
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /** Components */
            components: components["schemas"]["DecisionComponent"][];
            /** Binding Constraints */
            binding_constraints: string[];
            /** Assumptions */
            assumptions: string[];
            /**
             * Policy Version
             * @default synthetic-demo-1.0.0
             * @constant
             */
            policy_version: "synthetic-demo-1.0.0";
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Evidence Id */
            evidence_id: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Source */
            source: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "user_confirmed" | "synthetic_rule" | "derived";
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Fresh Until */
            fresh_until?: string | null;
            /** Confidence */
            confidence: number;
            /**
             * Status
             * @enum {string}
             */
            status: "confirmed" | "synthetic" | "derived";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /**
             * Data Scope
             * @constant
             */
            data_scope: "synthetic";
        };
        /**
         * RiskProfile
         * @enum {string}
         */
        RiskProfile: "standard" | "cautious" | "very_cautious";
        /** RuntimeBoundary */
        RuntimeBoundary: {
            /**
             * Data Scope
             * @constant
             */
            data_scope: "synthetic";
            /**
             * Provider
             * @constant
             */
            provider: "fake";
            /**
             * Planned Model
             * @constant
             */
            planned_model: "gpt-5.6-sol";
            /**
             * Persistence
             * @constant
             */
            persistence: "none";
            /**
             * Automatic Booking
             * @constant
             */
            automatic_booking: false;
        };
        /** TripInput */
        TripInput: {
            /** Flight Number */
            flight_number: string;
            /** Departure Airport */
            departure_airport: string;
            /**
             * Terminal
             * @default 待确认
             */
            terminal: string;
            /**
             * Scheduled Departure
             * Format: date-time
             */
            scheduled_departure: string;
            /** Departure Place */
            departure_place: string;
            /**
             * Checked Baggage
             * @default false
             */
            checked_baggage: boolean;
            /** @default cautious */
            risk_profile: components["schemas"]["RiskProfile"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    get_demo_trip_api_v1_demo_trip_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripInput"];
                };
            };
        };
    };
    preview_decision_api_v1_decisions_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
