# Load in the Nginx http context through /etc/nginx/conf.d/*.conf.
limit_req_zone $binary_remote_addr zone=mobility_public:10m rate=10r/s;
limit_conn_zone $binary_remote_addr zone=mobility_public_conn:10m;
